name: Create release and publish it
on: 
  workflow_dispatch:
    inputs:
      development-version:
        description: 'Version to set in development branch'     
        required: true
      release-version:
        description: 'Version to create/release'     
        required: true

jobs:
  maven-release:
    runs-on: ubuntu-latest
    env:
      DEVEL_VERSION: ${{ inputs.development-version }}
      RELEASE_VERSION: ${{ inputs.release-version }}
      MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
    steps:
      - name: Show versions
        run: |
          echo "Development : $DEVEL_VERSION"
          echo "Release : $RELEASE_VERSION"
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Create custom settings
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: '[{ "id": "ossrh", "username": "${env.MAVEN_USERNAME}", "password": "${env.MAVEN_PASSWORD}" }]'
      - name: Init Git info
        run: |
          git config --global user.email "$GITHUB_ACTOR@workflow.github.com"
          git config --global user.name "$GITHUB_ACTOR"
      - name: Release
        run: "mvn -B -DlocalCheckout=true -DscmCommentPrefix=\":bookmark: \" release:prepare -DreleaseVersion=$RELEASE_VERSION -DdevelopmentVersion=$DEVEL_VERSION"
      - name: Deploy on ossrh
        run: |
          mkdir /tmp/tag && cd /tmp/tag
          git clone https://github.com/tnb-software/odo-downloader.git && cd odo-downloader
          git checkout tags/odo-downloader-$RELEASE_VERSION -b odo-downloader-$RELEASE_VERSION
          mvn clean deploy -DskipTests
      - name: Create GitHub Release
        uses: fregante/release-with-changelog@v3
        with:
          tag: odo-downloader-$RELEASE_VERSION
          token: ${{ secrets.GITHUB_TOKEN }}
