on: 
  workflow_dispatch:
    inputs:
      development-version:
        description: 'Version to set in development branch'     
        required: true
      release-version:
        description: 'Version to create/release'     
        required: true

jobs:
  maven-release:
    runs-on: ubuntu-latest
    env:
      DEVEL_VERSION: ${{ inputs.development-version }}
      RELEASE_VERSION: ${{ inputs.release-version }}
      MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
    steps:
      - run: |
          echo "Development : $DEVEL_VERSION"
          echo "Release : $RELEASE_VERSION"
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: $MAVEN_USERNAME
          server-password: $MAVEN_PASSWORD
      - name: Release prepare
        run: "mvn -B -DscmCommentPrefix=\":bookmark: \" release:prepare -DreleaseVersion=$RELEASE_VERSION -DdevelopmentVersion=$DEVEL_VERSION"
      - name: Release perform
        run: "mvn release:perform"
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $RELEASE_VERSION
          release_name: $RELEASE_VERSION
          draft: false
          prerelease: false
