name: Publish branch to maven repository
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to publish'     
        required: true
        default: main

jobs:
  publish-branch:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ inputs.branch }}
      MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Create custom settings
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: '[{ "id": "ossrh", "username": "${env.MAVEN_USERNAME}", "password": "${env.MAVEN_PASSWORD}" }]'
      - name: Deploy on ossrh
        run: |
          mvn -B clean deploy -DskipTests
